Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using DocumentFormat.OpenXml.Office.CustomUI;
using DrugRelatedDeaths.API;
using DrugRelatedDeaths.DataAccess;
using DrugRelatedDeaths.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;

namespace DrugRelatedDeaths.Controllers
{
   
    public class DataController : Controller
    {
        public ApplicationDbContext dbContext;
       
        private readonly AppSettings _appSettings;
        public DataController(ApplicationDbContext context, IOptions<AppSettings> appSettings)
        {
            dbContext = context;
            _appSettings = appSettings.Value;
        }
        [HttpGet]
        public ActionResult Index(string Search_Data, string Drug_type)
        {
            var DrugList = new List<string>();
            var DrugQuery = from t1 in dbContext.MainObject
                             select t1.DescriptionofInjury;
            DrugList.AddRange(DrugQuery.Distinct());
                            




            ViewBag.Drug_type = new SelectList(DrugList);

            IList<MainObject.Drug_Info> drug_Infos = new List<MainObject.Drug_Info>();
            var emp = from q in dbContext.MainObject
                      select q;

            if (!String.IsNullOrEmpty(Search_Data))
            {
                emp = emp.Where(s => s.ResidenceCity.Contains(Search_Data));
            }

            if (!String.IsNullOrEmpty(Drug_type))
            {
                emp = emp.Where(s => s.DescriptionofInjury == Drug_type);
            }

            var myDrugList = emp.ToList();

            foreach (var empData in myDrugList)
            {
                drug_Infos.Add(new MainObject.Drug_Info()
                {
                    ID = empData.ID,
                    Sex = empData.Sex,
                    ResidenceCity = empData.ResidenceCity,
                    ResidenceCounty = empData.ResidenceCounty,
                    Race = empData.Race,
                    DescriptionofInjury = empData.DescriptionofInjury,
                    Date = empData.Date,
                    Age = empData.Age
                });
            }
            return View(drug_Infos);
        }
    


public IActionResult Bar()
        {
            int x = 0;
            int y = 0;
            int z = 0;
            int a = 0;
            int b = 0;
            int c = 0;
            APIHandler webHandler = new APIHandler();
            List<Drug> Drug1 = webHandler.GetObject1();
            foreach(Drug item in Drug1)
            { 
                if (item.Cocaine == "Y")
                {
                    x = x + 1;
                }
                if (item.Ethanol == "Y")
                {
                    y = y + 1;
                }
                if (item.Amphet == "Y")
                {
                    z = z + 1;
                }
                if (item.FentanylAnalogue == "Y")
                {
                    a = a + 1; 
                }
                if (item.Fentanyl == "Y")
                {
                    b = b + 1;
                }

                if (item.Tramad == "Y")
                {
                    c = c + 1;
                }
            }
            var lstmodel = new List<ReportViewModel>();
            lstmodel.Add(new ReportViewModel { DimensionOne = "Cocaine", Quantity = x });


            lstmodel.Add(new ReportViewModel { DimensionOne = "Ethanol", Quantity = y });
            lstmodel.Add(new ReportViewModel { DimensionOne = "Amphet", Quantity = z });
            lstmodel.Add(new ReportViewModel { DimensionOne = "Fentanyl", Quantity = b });
            lstmodel.Add(new ReportViewModel { DimensionOne = "Tramad", Quantity = c });
            lstmodel.Add(new ReportViewModel { DimensionOne = "FentanylAnalogue", Quantity = a });
            return View(lstmodel);
        }
            }

            
        }
    

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DrugRelatedDeaths.Models;
using DrugRelatedDeaths.API;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Mvc.ModelBinding.Binders;
using System.Collections;
using Microsoft.EntityFrameworkCore;
using DrugRelatedDeaths.DataAccess;
using Microsoft.Extensions.Options;


namespace DrugRelatedDeaths.Controllers
{
    public class HomeController : Controller
    {
        
        public ApplicationDbContext dbContext;
        private readonly AppSettings _appSettings;
        public HomeController(ApplicationDbContext context, IOptions<AppSettings> appSettings)
        {
            dbContext = context;
            _appSettings = appSettings.Value;
        }
       
        private readonly ILogger<HomeController> _logger;

        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Refresh()
        {

           
            APIHandler webHandler = new APIHandler();
            List<Drug> Drug1 = webHandler.GetObject1();

            APIHandler webHandler1 = new APIHandler();
            List<MainObject.Drug_Info> mainObj = webHandler1.GetObject();


            dbContext.MainObject.RemoveRange(dbContext.MainObject);
           
            dbContext.Drug.RemoveRange(dbContext.Drug);
            dbContext.SaveChanges();

             // ClearTables(Drugs);
            foreach (Drug item in Drug1)
            {   
               
                
                dbContext.Drug.Add(item);
            }
            //dbContext.SaveChanges();
            foreach ( MainObject.Drug_Info item in mainObj)
            {
                Console.WriteLine(item);
                dbContext.MainObject.Add(item);
            }
            dbContext.SaveChanges();
            var l1= new List<ReportViewModel>();
           var l2= new List<MainObject.Drug_Info>();
            int x = 0;
            foreach (MainObject.Drug_Info item1 in mainObj)
            {
                if (x < 20)
                {
                    l2.Add(item1);
                }
                else
                {
                    break;
                }
                x = x + 1;
            }


            return View(l2);
        }
      
        public IActionResult Index1()
        {


            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index1(MainObject.Drug_Info uc)
        {
            if (uc.ID == null)
            {
                ViewBag.message = "Please enter Id";
            }
            else
            {
                

                dbContext.MainObject.Add(uc);
                dbContext.SaveChanges();
                ViewBag.message = "The User" + uc.ID + "saved";
            }
            return View();

            
        }
        [Route("delete")]
        [HttpGet]
        public IActionResult Delete()
        {
            return View("Delete");
        }

        [Route("delete")]
        [HttpPost]
        public IActionResult Delete(string id)
        {
            
            if (id==null)
            {
                ViewBag.message = "Please enter id";
            }
            else
            {
                try
                {
                    dbContext.MainObject.Remove(dbContext.MainObject.Find(id));

                    dbContext.SaveChanges();
                    ViewBag.message = "The User" + id + "Deleted";
                }
                catch
                {
                    ViewBag.message = "No Matching ID Found";
                }

            }
            return View();
        }

        public IActionResult About()


        {
            return View();

        }
            public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
       
    } }
        
    

Views/Home/About.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Drug Related Accidents</title>
    <link rel="stylesheet" href="~/css/styles1.css">
    <!-- Fontawesome for apple icons -->
    <script src="https://kit.fontawesome.com/007aab5e0e.js" crossorigin="anonymous"></script>
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Ubuntu&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <!-- javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <section id="title-aboutgroup" background="images/jay-wennington-N_Y88TWmGwA-unsplash.jpg">
        <div class="brand">
            <a>Drug Related Accidents</a>
        </div>

        <div class="topnav" id="myTopnav">
            <a asp-area="" asp-controller="Home" asp-action="Index"> Home</a>
            <a asp-area="" asp-controller="Data" asp-action="Index"> Drug Related Accidents</a>
            <a asp-area="" asp-controller="Data" asp-action="Bar"> Statistics</a>
            <a asp-area="" asp-controller="Home" asp-action="About">AboutUs</a>
            <a asp-area="" asp-controller="Home" asp-action="Refresh">Refresh</a>
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                <i class="fa fa-bars"></i>
            </a>
        </div>
        <script>
            function myFunction() {
                var x = document.getElementById("myTopnav");
                if (x.className === "topnav") {
                    x.className += " responsive";
                } else {
                    x.className = "topnav";
                }
            }</script>

    </section>


    <!--About us -->
    <section id="Group5">
        <div class="Intro">
            <h3>
                We are group 5 of Distributed Information Systems of Spring 2020 at University of South Florida.The assignment is intended to help us learn html,css and js.Please find our contact details and contribution to project
                We developed a serach engine to find the restaurants near the user where the user can find the location
            </h3>
        </div>
        <div class="member-details">

            <div class="w3-row-padding">
                <div class="member w3-third">
                    <img class="image" src="~/images/Anu.jpg">
                    <b> <h3 class="names">Anu Kambalapally</h3></b>
                    <p>
                        Currently a student at USF's Business Analytics and Information Systems graduate program,
                        She designed the home page,Maps AboutUs page and also gave the template(basic design) of website.Her knowledge
                        of html and css made us create this website with ease.
                        <a href="https://github.com/anuyadav2494">Gitlink</a>
                    </p>
                </div>
                <div class="member w3-third">
                    <img class="image" src="~/images/Pranali.jpg">
                    <h3 class="names" align="center">Pranali Kanade</h3>
                    <p align="justify">
                        Currently a student at USF's Business Analytics and Information Systems graduate program,
                        She did the research on the data and came up with this idea to develop this website.She also designed logical
                        database model.
                    </p>
                </div>
                <div class="member w3-third">
                    <img class="image" src="~/images/Ballam.jpg">
                    <h3 class="names" align="center">Ballam Bikash</h3>
                    <p align="justify">
                        Currently a student at USF's Business Analytics and Information Systems graduate program,
                        He helped the team when ever struck with code and errors and developed the search page.
                        His insights helped us a lot for this project.
                    </p>
                </div>
            </div>
        </div>
        


    </section>
    <section id="database">
        <h2 align="center">
            The following is the data model for our website
        </h2>
        <img class="image" src="~/images/ER.jpeg">
    </section>





</body>

</html>

Views/Home/Delete.cshtml
@{
    Layout = null;
}

@model MainObject.Drug_Info;










<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Drug Related Accidents</title>
    <link rel="stylesheet" href="~/css/styles1.css">
    <!-- Fontawesome for apple icons -->
    <script src="https://kit.fontawesome.com/007aab5e0e.js" crossorigin="anonymous"></script>
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Ubuntu&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <!-- javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <section id="title-aboutgroup" background="images/jay-wennington-N_Y88TWmGwA-unsplash.jpg">
        <div class="brand">
            <a>Drug Related Accidents</a>
        </div>

        <div class="topnav" id="myTopnav">
            <a asp-area="" asp-controller="Home" asp-action="Index"> Home</a>
            <a asp-area="" asp-controller="Data" asp-action="Index"> Drug Related Accidents</a>
            <a asp-area="" asp-controller="Data" asp-action="Bar"> Statistics</a>
            <a asp-area="" asp-controller="Home" asp-action="About">AboutUs</a>
            <a asp-area="" asp-controller="Home" asp-action="Refresh">Refresh</a>
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                <i class="fa fa-bars"></i>
            </a>
        </div>
        <script>
            function myFunction() {
                var x = document.getElementById("myTopnav");
                if (x.className === "topnav") {
                    x.className += " responsive";
                } else {
                    x.className = "topnav";
                }
            }</script>

    </section>


    <h3>Drug Info</h3>
    <form method="post" asp-controller="home" asp-action="delete">
        <table cellpadding="2" cellspacing="2">
            <tr>
                <td>Id</td>
                <td>
                    <input type="text" asp-for="ID" />
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Delete" style="background:Aqua" /><a asp-controller="Data" asp-action="Index">
    <input type='button' value='Back to Search' style="background:Aqua" />
</a>
                </td>
            </tr>
            <b>@ViewBag.message</b>
        </table>
    </form>





</body>

</html>

Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Drug Related Accidents</title>
    <link rel="stylesheet" href="~/css/styles1.css">
    <!-- Fontawesome for apple icons -->
    <script src="https://kit.fontawesome.com/007aab5e0e.js" crossorigin="anonymous"></script>
    <!-- Google fonts -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Ubuntu&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <!-- javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <section id="title">
        <div class="brand">
            <a>Drug Related Accidents</a>
        </div>

        <div class="topnav" id="myTopnav">
            <a asp-area="" asp-controller="Home" asp-action="Index"> Home</a>
            <a asp-area="" asp-controller="Data" asp-action="Index"> Drug Related Accidents</a>
            <a asp-area="" asp-controller="Data" asp-action="Bar"> Statistics</a>
            <a asp-area="" asp-controller="Home" asp-action="About">AboutUs</a>
            <a asp-area="" asp-controller="Home" asp-action="Refresh">Refresh</a>

            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                <i class="fa fa-bars"></i>
            </a>
        </div>




        <h3 class="feature-h3">
            <b>
                FACTS & STATISTICS
            </b>
        </h3>
        <p class="text-p">
            According to the most recent World Drug Report, an estimated 585,000 people died as a result of drug use in 2017.

            Opioids account for the majority of drug-related deaths and in most cases such deaths are avoidable.
            More than 67,300 Americans died from drug-involved overdose in 2018, including illicit drugs and prescription opioids. Drug overdose deaths rose from 38,329 in 2010 to 70,237 in 2017; followed by a significant decrease in 2018 to 67,367 deaths. The bars are overlaid by lines showing the number of deaths by gender from 1999 to 2018
        </p>
        <p class="text-p">
            The number of drug overdose deaths decreased by 4% from 2017 to 2018.

            Still more than 67,000 people died from drug overdoses in 2018, making it a leading cause of injury-related death in the United States.

            Of those deaths, almost 70% involved a prescription or illicit opioid.
        </p>



    </section>
    <script>
        function myFunction() {
            var x = document.getElementById("myTopnav");
            if (x.className === "topnav") {
                x.className += " responsive";
            } else {
                x.className = "topnav";
            }
        }
    </script>



    <!-- Features -->
    <!-- <section id="features">
        <h3 class="feature-h3">
            <b>
                Let FindYourRestaurant Show You
                All the Restaurants in Town
            </b>
        </h3>
        <p class="text-p">
            There are plenty of restaurants, but none of them provide you with easy access or with appealing food photos from restaurants and restaurant menus across the country. At FindYourRestaurant, we tell you that we offer one of the best
            restaurants on the market. We list more than 450,000 restaurants (and counting!) of the most interesting, and most popular restaurants located throughout America. Next time you ask yourself, What are the best places to eat at near me?
            you will have your answer in no time.
        </p>
        <p class="text-p">
            Our goal is to introduce you, the hungry customer, to a broad range of restaurants  in locations you may not find on your own. Our platform  simply designed to be user-friendly and easy to navigate, leading
            you to some of the best restaurants in town. First, start by entering the location of the town ,city or zipcode in which you’re looking to dine in and BINGO! We will show you a list of
            restaurants in seconds!
        </p> -->
    </section>


</body>

</html>

Views/Home/Index1.cshtml
@{
    Layout = null;
}

@model MainObject.Drug_Info;











<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Drug Related Accidents</title>
    <link rel="stylesheet" href="~/css/styles1.css">
    <!-- Fontawesome for apple icons -->
    <script src="https://kit.fontawesome.com/007aab5e0e.js" crossorigin="anonymous"></script>
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Ubuntu&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <!-- javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <section id="title-aboutgroup" background="images/jay-wennington-N_Y88TWmGwA-unsplash.jpg">
        <div class="brand">
            <a>Drug Related Accidents</a>
        </div>

        <div class="topnav" id="myTopnav">
            <a asp-area="" asp-controller="Home" asp-action="Index"> Home</a>
            <a asp-area="" asp-controller="Data" asp-action="Index"> Drug Related Accidents</a>
            <a asp-area="" asp-controller="Data" asp-action="Bar"> Statistics</a>
            <a asp-area="" asp-controller="Home" asp-action="About">AboutUs</a>
            <a asp-area="" asp-controller="Home" asp-action="Refresh">Refresh</a>
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                <i class="fa fa-bars"></i>
            </a>
        </div>
        <script>
            function myFunction() {
                var x = document.getElementById("myTopnav");
                if (x.className === "topnav") {
                    x.className += " responsive";
                } else {
                    x.className = "topnav";
                }
            }</script>

    </section>


   
    <h1>Add </h1>

    <hr />
    <div class="row" style="justify-content: center ">
        <div class="col-md-11" style="align-items: center">
            <form asp-action="Index1">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group" >
                    <label asp-for="ID" class="control-label"></label>
                    <input asp-for="ID" class="form-control" />
                    <span asp-validation-for="ID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Sex" class="control-label"></label>
                    <input asp-for="Sex" class="form-control" />

                </div>
                <div class="form-group">
                    <label asp-for="ResidenceCity" class="control-label"></label>
                    <input asp-for="ResidenceCity" class="form-control" />

                </div>
                <div class="form-group">
                    <label asp-for="ResidenceCounty" class="control-label"></label>
                    <input asp-for="ResidenceCounty" class="form-control" />

                </div>
                <div class="form-group">
                    <label asp-for="Date" class="control-label"></label>
                    <input asp-for="Date" class="form-control" />

                </div>
                <div class="form-group">
                    <label asp-for="Race" class="control-label"></label>
                    <input asp-for="Race" class="form-control" />

                </div>
                <div class="form-group">
                    <label asp-for="Age" class="control-label"></label>
                    <input asp-for="Age" class="form-control" />

                </div>
                <div class="form-group">
                    <label asp-for="DescriptionofInjury" class="control-label"></label>
                    <input asp-for="DescriptionofInjury" class="form-control" />

                </div>
                <div class="form-group">
                    <input type="submit" value="Add" style="background:Aqua" class="btn btn-primary" /><a asp-controller="Data" asp-action="Index">
    <input type='button' value='Back to Search' style="background:Aqua" />
</a>
                    
                </div>
                <b>@ViewBag.message</b>
            </form>
        </div>
    </div>

    <div>
       
    </div>
    <div>

        <h1>   </h1>
    </div>


    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }


</body>

</html>